{% set name = "performance" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35fc9028337eada5f816f39fe6fae6875beb925d4db828e4d74a7ae468a05efb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperformance = performance.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - perf
    - six

test:
  imports:
    - performance
  commands:
    - pyperformance --help

about:
  home: http://github.com/python/perf/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Python Performance Benchmark Suite'
  doc_url: http://pyperformance.readthedocs.io/
  dev_url: https://github.com/python/perf/

extra:
  recipe-maintainers:
    - dougalsutherland
